name: Check and Format
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: curl https://raw.githubusercontent.com/dhhyi/travel-packlist/refs/heads/rules-cmdl/index.cjs | node - --format --error-on-warnings my-rules.txt

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "formatting"
